fileVersion: 1
id: "35"
mappingDefinitions:
  AWAY:
    database: NOLAN_DB
    schema: WHATINTARNATION
  HOME:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
name: New Environment
type: Environment
