fileVersion: 1
id: "4"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: NOLAN_DB
    schema: STAGE
name: New Environment
type: Environment
