fileVersion: 1
id: "43"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: NOLAN_DB
    schema: HELLOTWO
name: New Environment
type: Environment
