fileVersion: 1
id: "27"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: NOLAN_DB
    schema: FRICK
name: New Environment
type: Environment
